version: "3"
services:
  frontend-ipat:
    image: ipat-app
    ports:
      - "80:3001"
    networks:
      - ipat
    depends_on:
      - backend-ipat

  backend-ipat:
    image: ipat-app-backend
    ports:
      - "5001:5001"
    networks:
      - ipat

networks:
  ipat:
    driver: bridge